title: "[ADR] "
labels: ["ADR"]
body:
  - type: dropdown
    attributes:
      label: Status
      options:
        - Draft
        - Proposed
        - Accepted
        - Rejected
        - Deprecated
        - Superseded
      default: 0
    validations:
      required: true
  - type: markdown
    validations:
      required: true
    attributes:
      description: >
        What is the issue that we're seeing that is motivating this decision or change?
