title: "[ADR] "
labels: ["ADR"]
body:
  - type: dropdown
    attributes:
      label: Status
      options:
        - Draft
        - Proposed
        - Accepted
        - Rejected
        - Deprecated
        - Superseded
      default: 0
    validations:
      required: true
