title: "[ADR] "
labels: ["ADR"]
body:
  - type: dropdown
    attributes:
      label: Status
      options:
        - Draft
        - Proposed
        - Accepted
        - Rejected
        - Deprecated
        - Superseded
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      label: Context
      description: "What is the issue that we are seeing that is motivating this decision or change?"
  - type: markdown
    attributes:
      label: Decision
      description: "What is the change that we are proposing and/or doing?"
  - type: markdown
    attributes:
      label: Consequences
      description: "What becomes easier or more difficult to do because of this change?"
